### ISSUE TITLE
Some Changes using Css properties.

### ISSUE THREAD

**Issue by dvig14** [IEEE-SB-GECBH/Cheatsheet-Hacktoberfest2022#1]
can u assign me this.

**Comment by gouthamrajesh** [comment]
Please proceed with your changes and sent a PR.
! Happy Hacking !

**Comment by dvig14** [comment]
Tnx😊

**Comment by gouthamrajesh** [comment]
Thank You for your contribution. Hoping to see you contributing more to Open Source.
! Happy Hacking !

**Comment by dvig14** [comment]
Thank you! 😊
