### ISSUE TITLE
Image broken and click is working only on the text of the box

### ISSUE THREAD

**Issue by vaibhav-1508** [IEEE-SB-GECBH/Cheatsheet-Hacktoberfest2022#6]
![image](https://user-images.githubusercontent.com/96713176/194570920-8ae7b47b-6cfd-4d64-9d56-750aafe9cc52.png)
The click would only work if I click on the text if the box

**Comment by vaibhav-1508** [comment]
can i work on this issue

**Comment by gouthamrajesh** [comment]
Please proceed Champ 👍🏻
! Happy Hacking !
